#! /bin/sh

## Get colors from .Xresources -------------------------------#
xrdb ~/.config/bspwm/Xresources

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#3f51b5" 
bspc config normal_border_color "#080808"
bspc config active_border_color "#E9698E"
bspc config presel_feedback_color "#47BAE8"


sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc rule -r *:*

bspc rule -a Code desktop='^4' follow=on focus=on
bspc rule -a Nautilus desktop='^2' follow=on focus=on
bspc rule -a Nm-connection-editor state=floating follow=on focus=on
bspc rule -a Gnome-terminal state=floating follow=on focus=on
bspc rule -a Google-chrome desktop='^1' follow=on focus=on border=off
bspc rule -a Nitrogen state=floating follow=on focus=on
bspc rule -a Gimp desktop='^5' state=floating follow=on

nitrogen --restore &
compton &
/usr/bin/numlockx on
/usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1 &
xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh &

clipmenud &
dunst &
flameshot &

xsetroot -cursor_name left_ptr

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
